#!/usr/bin/env bash
set -euo pipefail

# Reset
Color_Off='\033[0m' # Text Reset

# Regular Colors
Red='\033[0;31m'   # Red
Green='\033[0;32m' # Green
Dim='\033[0;2m'    # White

# Bold
Bold_Green='\033[1;32m' # Bold Green
Bold_White='\033[1m'    # Bold White

error() {
    echo -e "${Red}error${Color_Off}:" "$@" >&2
    exit 1
}

info() {
    echo -e "${Dim}$@ ${Color_Off}"
}

info_bold() {
    echo -e "${Bold_White}$@ ${Color_Off}"
}

success() {
    echo -e "${Green}$@ ${Color_Off}"
}

tildify() {
    if [[ $1 = $HOME/* ]]; then
        local replacement=\~/

        echo "${1/$HOME\//$replacement}"
    else
        echo "$1"
    fi
}

case $(uname -ms) in
'Darwin x86_64')
    target=x86_64-apple-darwin
    ;;
'Darwin arm64')
    target=aarch64-apple-darwin
    ;;
'Linux x86_64')
    target=x86_64-unknown-linux-musl
    ;;
*)
    error "The Dune Developer Preview does not currently support $(uname -ms)."
esac

today=$(date +"%Y-%m-%d")
tar_target_name="dune-$today-$target"
tar_target="$tar_target_name.tar.gz"
dune_tar_uri="https://get.dune.build/$today/$target/$tar_target"

install_dir=$HOME/.dune
bin_dir=$install_dir/bin
tmp_dir=$install_dir/tmp
exe=$bin_dir/dune
tmp_tar="$tmp_dir/$tar_target"
tmp_tar_dir="$tmp_dir/$tar_target_name"
tmp_exe="$tmp_tar_dir/dune"
tilde_bin_dir=$(tildify $bin_dir)

command -v tar >/dev/null 2>&1 ||
    error "Failed to find tar. This script needs tar to be able to install dune."

if [[ ! -d $bin_dir ]]; then
    mkdir -p "$bin_dir" ||
        error "Failed to create install directory \"$bin_dir\""
fi

if [[ ! -d $tmp_dir ]]; then
    mkdir -p "$tmp_dir" ||
        error "Failed to create temporary directory \"$tmp_dir\""
fi

curl --fail --location --progress-bar --output "$tmp_tar" "$dune_tar_uri" ||
    error "Failed to download dune tar from \"$dune_tar_uri\""

tar -xvf "$tmp_tar" -C $tmp_dir 2>&1 > /dev/null ||
    error "Failed to extract dune archive content from \"$tmp_tar\""

mv $tmp_exe $exe ||
    error "Failed to move executable from $tmp_exe to $exe"

(rm "$tmp_tar" && rmdir "$tmp_tar_dir" && rmdir "$tmp_dir") ||
    error "Failed to delete the temporary directory $tmp_dir"


success "dune $target was installed successfully to $Bold_Green$(tildify "$exe")"

echo

case $(basename "$SHELL") in
fish)
    commands=(
        "set --export PATH $bin_dir \$PATH"
    )

    fish_config=$HOME/.config/fish/config.fish
    tilde_fish_config=$(tildify "$fish_config")

    if [[ -w $fish_config ]]; then
        {
            echo -e '\n# dune'

            for command in "${commands[@]}"; do
                echo "$command"
            done
        } >>"$fish_config"

        info "Added \"$tilde_bin_dir\" to \$PATH in \"$tilde_fish_config\""

        refresh_command="source $tilde_fish_config"
    else
        echo "Manually add the directory to $tilde_fish_config (or similar):"

        for command in "${commands[@]}"; do
            info_bold "  $command"
        done
    fi
    ;;
zsh)

    commands=(
        "export PATH=\"$bin_dir:\$PATH\""
    )

    zsh_config=$HOME/.zshrc
    tilde_zsh_config=$(tildify "$zsh_config")

    if [[ -w $zsh_config ]]; then
        {
            echo -e '\n# dune'

            for command in "${commands[@]}"; do
                echo "$command"
            done
        } >>"$zsh_config"

        info "Added \"$tilde_bin_dir\" to \$PATH in \"$tilde_zsh_config\""

        refresh_command="exec $SHELL"
    else
        echo "Manually add the directory to $tilde_zsh_config (or similar):"

        for command in "${commands[@]}"; do
            info_bold "  $command"
        done
    fi
    ;;
bash)

    commands=(
        "export PATH=$bin_dir:\$PATH"
    )

    bash_configs=(
        "$HOME/.bashrc"
        "$HOME/.bash_profile"
    )

    if [[ ${XDG_CONFIG_HOME:-} ]]; then
        bash_configs+=(
            "$XDG_CONFIG_HOME/.bash_profile"
            "$XDG_CONFIG_HOME/.bashrc"
            "$XDG_CONFIG_HOME/bash_profile"
            "$XDG_CONFIG_HOME/bashrc"
        )
    fi

    set_manually=true
    for bash_config in "${bash_configs[@]}"; do
        tilde_bash_config=$(tildify "$bash_config")

        if [[ -w $bash_config ]]; then
            {
                echo -e '\n# dune'

                for command in "${commands[@]}"; do
                    echo "$command"
                done
            } >>"$bash_config"

            info "Added \"$tilde_bin_dir\" to \$PATH in \"$tilde_bash_config\""

            refresh_command="source $bash_config"
            set_manually=false
            break
        fi
    done

    if [[ $set_manually = true ]]; then
        echo "Manually add the directory to $tilde_bash_config (or similar):"

        for command in "${commands[@]}"; do
            info_bold "  $command"
        done
    fi
    ;;
*)
    echo 'Manually add the directory to ~/.bashrc (or similar):'
    info_bold "  export PATH=\"$bin_dir:\$PATH\""
    ;;
esac

echo
info "To get started, run:"
echo

if [[ $refresh_command ]]; then
    info_bold "  $refresh_command"
fi

info_bold "  dune --help"
