#!/bin/sh
# This script is meant to be POSIX compatible, to work on as many different systems as possible.
# Please try to stick to this. Use a tool like shellcheck to validate changes.
set -eu

# the whole body of the script is wrapped in a function so that a partially
# downloaded script does not get executed by accident. The function is called
# at the end
main () {

# Reset
Color_Off='\033[0m' # Text Reset

# Regular Colors
Red='\033[0;31m'   # Red
Green='\033[0;32m' # Green
White='\033[0;0m'  # White

# Bold
Bold_Green='\033[1;32m' # Bold Green
Bold_White='\033[1m'    # Bold White

error() {
    printf "%berror%b: %s\n" "${Red}" "${Color_Off}" "$*" >&2
    exit 1
}

info() {
     printf "%b%s %b" "${White}" "$*" "${Color_Off}"
}

info_bold() {
    printf "%b%s %b" "${Bold_White}" "$*" "${Color_Off}"
}

success() {
    printf "%b%s %b" "${Green}" "$*" "${Color_Off}"
}

success_bold() {
    printf "%b%s %b" "${Bold_Green}" "$*" "${Color_Off}"
}

tildify() {
    case "$1" in
    "$HOME"/*)
        tilde_replacement=\~
        echo "$1" | sed "s|$HOME|$tilde_replacement|g"
        ;;
    *)
        echo "$1"
        ;;
    esac
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

ensure_command() {
    command_exists "$1" ||
        error "Failed to find \"$1\". This script needs \"$1\" to be able to install dune."
}

case $(uname -ms) in
'Darwin x86_64')
    target=x86_64-apple-darwin
    ;;
'Darwin arm64')
    target=aarch64-apple-darwin
    ;;
'Linux x86_64')
    target=x86_64-unknown-linux-musl
    ;;
*)
    error "The Dune Developer Preview does not currently support $(uname -ms)."
esac

tar_target_name="dune-$target"
tar_target="$tar_target_name.tar.gz"
dune_tar_uri="https://preview.dune.build/latest/$target"

install_dir="$HOME/.local"
bin_dir="${install_dir}/bin"
share_dir="${install_dir}/share/dune"
completions_dir="${share_dir}/completions"
env_dir="${share_dir}/env"

tmp_dir="$(mktemp -d -t dune-install.XXXXXXXXXX)"
if [ ! $? ]; then
    error "Failed to create temporary directory \"$tmp_dir\""
fi
trap 'rm -rf "${tmp_dir}"' EXIT

exe="$bin_dir/dune"
tmp_tar="$tmp_dir/$tar_target"

ensure_command "tar"
# technically gunzip probably but they will both exist
ensure_command "gzip"
ensure_command "curl"

# determine whether we can use --no-same-owner to force tar to extract with user permissions
touch "${tmp_dir}/tar-detect"
tar cf "${tmp_dir}/tar-detect.tar" -C "${tmp_dir}" tar-detect
if tar -C "${tmp_dir}" -xf "${tmp_dir}/tar-detect.tar" --no-same-owner; then
  tar_owner="--no-same-owner"
else
  tar_owner=""
fi

if [ ! -d "$bin_dir" ]; then
    mkdir -p "$bin_dir" ||
        error "Failed to create install directory \"$bin_dir\""
fi

curl --fail --location --progress-bar \
    --proto '=https' --tlsv1.2 \
    --output "$tmp_tar" "$dune_tar_uri" ||
        error "Failed to download dune tar from \"$dune_tar_uri\""


tar -xf "$tmp_tar" -C "$tmp_dir" "${tar_owner}" > /dev/null 2>&1 ||
    error "Failed to extract dune archive content from \"$tmp_tar\""

# locate the name of the directory that was unpacked in the tarball
tmp_tar_dir="$(find "$tmp_dir" -mindepth 1 -maxdepth 1 -type d)"

tmp_exe="$tmp_tar_dir/dune"

mv "$tmp_exe" "$exe" ||
    error "Failed to move executable from $tmp_exe to $exe"

mkdir -p "${share_dir}"

if [ -d "${env_dir}" ]; then
    rm -r "${env_dir}"
fi

mv "$tmp_tar_dir/env" "${share_dir}" ||
    error "Failed to move env from \"$tmp_tar_dir\" to \"$share_dir\""

if [ -d "${completions_dir}" ]; then
    rm -r "${completions_dir}"
fi
mv "$tmp_tar_dir/completions" "${share_dir}" ||
    error "Failed to move completions from \"$tmp_tar_dir\" to \"$share_dir\""

mv "$tmp_tar_dir"/tool-wrappers/* "$bin_dir" ||
    error "Failed to move tool wrapper scripts from \"$tmp_tar_dir\" to \"$bin_dir\""

success "dune $target was installed successfully to"
success_bold "$(tildify "$exe")"
echo
echo

# populate rev-store
cache_dir="${XDG_CACHE_HOME:-$HOME/.cache/dune}"
rev_store_dir="${cache_dir}/git-repo"

unpack_tar() {
    tar xf "$1" -C "${tmp_dir}" "${tar_owner}"
}

unpack_tar_zstd() {
    filename="$1"
    zstd --decompress --rm --quiet "${filename}"
    tarball="${filename%%.zst}"
    unpack_tar "$tarball"
}

opam_repo_tarball_url() {
    release="$1"
    archive="$2"
    repo="ocaml-dune/opam-repository-snapshots"
    printf "https://github.com/%s/releases/download/%s/%s" "${repo}" "${release}" "${archive}"
}

if [ ! -d "${rev_store_dir}" ] ; then
    release="opam-repository-d910b0617a51ea90e4547db13a509962fc504f70"
    if command_exists "zstd"; then
        # if we have zstd download the zstd compressed tarball
	opam_repo_tarball=$(opam_repo_tarball_url "${release}" "git-repo.tar.zst")
	opam_repo_filename="${tmp_dir}/git-repo.tar.zst"
	extract_command="unpack_tar_zstd"
    else
	# why not .gz? decompressing gz takes ~4x as long as zstd, thus the meager
	# savings of 6.5% in size is not worth the additional time it takes to
	# decompress. zstd wins on both size and decompression speed
	opam_repo_tarball=$(opam_repo_tarball_url "${release}" "git-repo.tar")
	opam_repo_filename="${tmp_dir}/git-repo.tar"
	extract_command="unpack_tar"
    fi

    curl --fail --location --progress-bar \
        --proto '=https' --tlsv1.2 \
        --output "${opam_repo_filename}" \
        "${opam_repo_tarball}" ||
	    error "Failed to download opam-repository snapshot from \"$opam_repo_tarball}\""

    # extract_command creates a folder called `git-repo`
    "${extract_command}" "${opam_repo_filename}"

    mkdir -p "${cache_dir}"
    mv "${tmp_dir}/git-repo" "${cache_dir}" ||
        error "Failed to move revision cache to cache location ${cache_dir}"

    success "Revision cache was populated successfully"
    echo
fi

already_installed=false

unsubst_home() {
    echo "$1" | sed -e "s#^$HOME#\$HOME#"
}

remove_home() {
    echo "$1" | sed -e "s#^$HOME/##" | sed -e 's#^/##'
}

case $(basename "${SHELL:-*}") in
fish)
    env="${env_dir}/env.fish"
    env_file=$(unsubst_home "${env}")

    fish_config=$HOME/.config/fish/config.fish
    tilde_fish_config=$(tildify "$fish_config")

    # deliberately omit the home directory from the pattern so "~" and "$HOME" can be used interchangeably
    if [ -f "$fish_config" ] && match=$(grep -n "$(remove_home "${env}")" "$fish_config"); then
        echo "Shell configuration for dune appears to already exist in \"$fish_config\":"
        echo "$match"
        already_installed=true
        refresh_command="source $tilde_fish_config"
    elif [ -w "$fish_config" ]; then
        printf "\n# dune\n%s\n" "source $env_file" >> "$fish_config"

        info "Sourced \"$env_file\" in \"$tilde_fish_config\""
        echo

        refresh_command="source $tilde_fish_config"
    else
        echo "To use dune you will need to source the file \"$env_file\""
        echo
    fi
    ;;

zsh)
    env="${env_dir}/env.zsh"
    env_file=$(unsubst_home "${env}")

    zsh_config=$HOME/.zshrc
    tilde_zsh_config=$(tildify "$zsh_config")

    # deliberately omit the home directory from the pattern so "~" and "$HOME" can be used interchangeably
    if [ -f "$zsh_config" ] && match=$(grep -n "$(remove_home "${env}")" "$zsh_config"); then
        echo "Shell configuration for dune appears to already exist in \"$zsh_config\":"
        echo "$match"
        already_installed=true
        refresh_command="exec $SHELL"
    elif [ -w "$zsh_config" ]; then
        printf "\n# dune\n%s\n" "source $env_file" >>"$zsh_config"

        info "Sourced \"$env_file\" in \"$tilde_zsh_config\""
        echo

        refresh_command="exec $SHELL"
    else
        echo "To use dune you will need to source the file \"$env_file\""
        echo
    fi
    ;;

bash)
    env="${env_dir}/env.bash"
    env_file=$(unsubst_home "${env}")

    bash_configs="$HOME/.bashrc $HOME/.bash_profile"

    if [ "${XDG_CONFIG_HOME:-}" ]; then
        bash_configs="$bash_configs $XDG_CONFIG_HOME/.bash_profile $XDG_CONFIG_HOME/.bashrc $XDG_CONFIG_HOME/bash_profile $XDG_CONFIG_HOME/bashrc"
    fi

    for bash_config in $bash_configs; do
        # deliberately omit the home directory from the pattern so "~" and "$HOME" can be used interchangeably
	if [ -f "$bash_config" ] && match=$(grep -n "$(remove_home "${env}")" "$bash_config"); then
            echo "Shell configuration for dune appears to already exist in \"$bash_config\":"
            echo "$match"
            refresh_command="source $bash_config"
            already_installed=true
            break
        fi
    done

    if [ "$already_installed" = false ]; then
        set_manually=true
        for bash_config in $bash_configs; do
            tilde_bash_config=$(tildify "$bash_config")

            if [ -w "$bash_config" ]; then
                printf "\n# dune\n%s\n" "source $env_file" >>"$bash_config"

                info "Sourced \"$env_file\" in \"$tilde_bash_config\""
                echo

                refresh_command="source $bash_config"
                set_manually=false
                break
            fi
        done

        if [ $set_manually = true ]; then
            echo "To use dune you will need to source the file \"$env_file\""
            echo
        fi
    fi
    ;;

*|unset)
    env="${env_dir}/env.bash"
    env_file=$(unsubst_home "${env}")

    echo "To use dune you will need to source the file \"$env_file\" (or similar as appropriate for your shell)"
    info_bold "  export PATH=\"$bin_dir:\$PATH\""
    echo
    ;;
esac


if [ "$already_installed" = false ]; then
    echo
    info "To get started, run:"
    echo

    if [ -n "${refresh_command+x}" ]; then
        info_bold "  $refresh_command"
        echo
    fi

    info_bold "  dune --help"
    echo
fi

# end of main
}

main
